### ISSUE TITLE
ValueError in pd.option_contex

### ISSUE THREAD

**Issue by siranipour** [NNPDF/reportengine#28]
This line now raises a `ValueError: Value must be a nonnegative integer or None`

https://github.com/NNPDF/reportengine/blob/9d34899171729f95b221add85347f08a9a41d764/src/reportengine/table.py#L53

Think it may have changed in the new pandas.

**Comment by siranipour** [comment]
Replacing the `-1` with the default `50` works but I don't really know what the knock on effects are

**Comment by Zaharid** [comment]
Seems pandas introduced some breakage, and on top of it, contrary to what the docs here say

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.set_option.html

None doesn't work properly.

**Comment by Zaharid** [comment]
Actually None works for 1.0 but no for older versions, so this is creating breakage for no reason...

**Comment by siranipour** [comment]
Shall we bother updating it in reportengine or keep the old pandas version in the conda recipe?

**Comment by Zaharid** [comment]
I guess we can update it and change the recipe to specify that it works for pandas above 1.0. But then we need to fix for good the `.ix` in vp.

**Comment by siranipour** [comment]
Ok I'll make a PR here then
