### ISSUE TITLE
development installation metadata doesn't appear to match master

### ISSUE THREAD

**Issue by wilsonmr** [NNPDF/reportengine#42]
I was just looking to test out lockfiles and followed the dev install instructions and noted that my curio version got downgraded.

I think the curio version got unlocked here: https://github.com/NNPDF/reportengine/commit/f4446a68bd92b9bd1db2415f2cc3f8ab866b8f13

But perhaps the flit file needs to be regenerated?

https://github.com/NNPDF/reportengine/blob/d05776846c32ce92e63462256a71954fe77b6bb5/pyproject.toml#L27

**Comment by wilsonmr** [comment]
On reading the flit read me I guess this file only gets generated once and just needs to be updated?

**Comment by Zaharid** [comment]
It wasn't so much unlocked as me stopping caring about the various error conditions...
