### ISSUE TITLE
Version available in pypi doesn't work correctly in Mac OS

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/reportengine#54]
I haven't pinpointed the problem, but the collection over experiments in NNPDF was not working correctly (and so I was getting a mismatch of arrays).

Installing (with `pip install .`) from this repository directly fixed the problem.

If I have time I'll try to debug it a bit more (as far as I can see no package was updated and the version of report engine is the same). For the time being I'm leaving this issue here as information for other users.

**Comment by scarlehoff** [comment]
No, the package version seemed to be the same when I opened the issue.
As said originally, once I have time I will try to debug a bit more... if when I have time I haven't forgotten (again).

This is for the pip package, things not installed with conda but pip only.

**Comment by Zaharid** [comment]
I pushed an updated package. Maybe that will fix things.

**Comment by scarlehoff** [comment]
Seems to work now, thanks!
