### ISSUE TITLE
Consider vendoring `curio`

### ISSUE THREAD

**Issue by RaitoBezarius** [NNPDF/reportengine#58]
Unfortunately, its author decided that software didn't need releases anymore: https://github.com/dabeaz/curio#important-notice-october-25-2022

This makes packaging this package a bit harder than necessary, please consider vendoring the dependency or using something else if you don't need it. :)

Thank you!

**Comment by Zaharid** [comment]
This should be fixed by #56.

**Comment by RoyStegeman** [comment]
This has been addressed in #56
